export const fields = {
  customer: {
    type: 'async',
    label: 'Customer',
    required: true,
    entity: 'client',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  vehicle: {
    type: 'async',
    label: 'Vehicle',
    required: true,
    entity: 'vehicle',
    displayLabels: ['vin', 'make', 'model'],
    dataIndex: ['vin'],
    searchFields: 'vin,make,model',
  },
  serviceType: {
    type: 'select',
    label: 'Service Type',
    required: true,
    options: [
      { value: 'oil_change', label: 'Oil Change' },
      { value: 'tire_rotation', label: 'Tire Rotation' },
      { value: 'brake_service', label: 'Brake Service' },
      { value: 'engine_repair', label: 'Engine Repair' },
      { value: 'transmission_service', label: 'Transmission Service' },
      { value: 'electrical', label: 'Electrical' },
      { value: 'diagnostic', label: 'Diagnostic' },
      { value: 'inspection', label: 'Inspection' },
      { value: 'maintenance', label: 'Maintenance' },
      { value: 'other', label: 'Other' },
    ],
  },
  status: {
    type: 'select',
    label: 'Status',
    options: [
      { value: 'scheduled', label: 'Scheduled' },
      { value: 'checked_in', label: 'Checked In' },
      { value: 'in_progress', label: 'In Progress' },
      { value: 'awaiting_parts', label: 'Awaiting Parts' },
      { value: 'awaiting_approval', label: 'Awaiting Approval' },
      { value: 'completed', label: 'Completed' },
      { value: 'invoiced', label: 'Invoiced' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    default: 'scheduled',
  },
  scheduledDate: {
    type: 'date',
    label: 'Scheduled Date',
    required: true,
  },
  estimatedCompletionDate: {
    type: 'date',
    label: 'Estimated Completion',
  },
  mileageIn: {
    type: 'number',
    label: 'Mileage In',
  },
  technician: {
    type: 'async',
    label: 'Technician',
    entity: 'admin',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  advisor: {
    type: 'async',
    label: 'Service Advisor',
    entity: 'admin',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  customerConcerns: {
    type: 'textarea',
    label: 'Customer Concerns',
  },
  technicianNotes: {
    type: 'textarea',
    label: 'Technician Notes',
  },
  recommendations: {
    type: 'textarea',
    label: 'Recommendations',
  },
  taxRate: {
    type: 'number',
    label: 'Tax Rate (%)',
    default: 0,
  },
};
