export const fields = {
  customer: {
    type: 'async',
    label: 'Customer',
    required: true,
    entity: 'client',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  vehicle: {
    type: 'async',
    label: 'Vehicle',
    required: true,
    entity: 'vehicle',
    displayLabels: ['vin', 'make', 'model'],
    dataIndex: ['vin'],
    searchFields: 'vin,make,model',
  },
  appointmentDate: {
    type: 'date',
    label: 'Appointment Date',
    required: true,
  },
  appointmentTime: {
    type: 'string',
    label: 'Appointment Time',
    required: true,
    placeholder: 'HH:MM (e.g., 09:00)',
  },
  duration: {
    type: 'number',
    label: 'Duration (minutes)',
    default: 60,
  },
  serviceType: {
    type: 'select',
    label: 'Service Type',
    required: true,
    options: [
      { value: 'oil_change', label: 'Oil Change' },
      { value: 'tire_rotation', label: 'Tire Rotation' },
      { value: 'brake_service', label: 'Brake Service' },
      { value: 'engine_repair', label: 'Engine Repair' },
      { value: 'transmission_service', label: 'Transmission Service' },
      { value: 'electrical', label: 'Electrical' },
      { value: 'diagnostic', label: 'Diagnostic' },
      { value: 'inspection', label: 'Inspection' },
      { value: 'maintenance', label: 'Maintenance' },
      { value: 'other', label: 'Other' },
    ],
  },
  status: {
    type: 'select',
    label: 'Status',
    options: [
      { value: 'scheduled', label: 'Scheduled' },
      { value: 'confirmed', label: 'Confirmed' },
      { value: 'arrived', label: 'Arrived' },
      { value: 'in_service', label: 'In Service' },
      { value: 'completed', label: 'Completed' },
      { value: 'no_show', label: 'No Show' },
      { value: 'cancelled', label: 'Cancelled' },
    ],
    default: 'scheduled',
  },
  technician: {
    type: 'async',
    label: 'Technician',
    entity: 'admin',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  advisor: {
    type: 'async',
    label: 'Service Advisor',
    entity: 'admin',
    displayLabels: ['name'],
    dataIndex: ['name'],
    searchFields: 'name,email',
  },
  customerConcerns: {
    type: 'textarea',
    label: 'Customer Concerns',
  },
  specialInstructions: {
    type: 'textarea',
    label: 'Special Instructions',
  },
  estimatedCost: {
    type: 'number',
    label: 'Estimated Cost',
  },
  contactPhone: {
    type: 'phone',
    label: 'Contact Phone',
  },
  contactEmail: {
    type: 'email',
    label: 'Contact Email',
  },
};
